//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_ACCESS_LAYER.DataModels
{
    using System;
    
    public partial class SP_GeAll_SchedStudentDetailt_Result
    {
        public System.Guid ScsId { get; set; }
        public string FullName { get; set; }
        public string WeName { get; set; }
        public string ShiftName { get; set; }
        public string CourseName { get; set; }
        public string Description { get; set; }
    }
}
